version: '3.7'

services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
  mysql:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ../api/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 30
  api:
    container_name: api
    build: ../api
    restart: always
    env_file:
      - ../api/.env
    ports:
      - 3000:3000
    depends_on:
      - mysql
      # mysql:
      #   condition: service_healthy
volumes:
  mysql-volume: