version: "3.9"  # optional since v1.27.0
services:
  mysql:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 30
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql-volume: