name: Build and deploy Node.js app to linode
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add mask
        run: |
          echo "::add-mask::{{ secrets.ENV_FILE }}" 
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Try remove Kubernetes config map
        run: |
          kubectl delete configmap trolley-management-api-config
        continue-on-error: true
      - name: Docker Build and Push, Kubernetes apply
        run: |
          docker build --tag landonrepp/trolley-management-api:${{ github.sha }} --tag landonrepp/trolley-management-api:latest ./api
          docker push landonrepp/trolley-management-api:${{ github.sha }}
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
          cat <<EOF > ./api/.env
          ${{ secrets.ENV_FILE }}
          EOF
      - name: replace config values in kube config
        run: |
          sed -i'' -e 's/DOCKERHUB_USERNAME/${{ secrets.DOCKERHUB_USERNAME }}/g' -e 's/DOCKERHUB_REPOSITORY/trolley-management-api/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' -e "s/DOCKER_CONFIG/$DOCKER_CONFIG/g" ./build/trolley-management-service.yml
          more ./build/trolley-management-service.yml
      - name: deploy to kubernetes cluster
        run: |
          kubectl create configmap trolley-management-api-config --from-env-file=./api/.env -o yaml &>/dev/null
          kubectl apply -f ./build/trolley-management-service.yml
          