name: Build and deploy Node.js app to linode
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Docker Build and Push, Kubernetes apply
        run: |
          docker build --tag landonrepp/trolley-management-api:${{ github.sha }} ./api
          docker push landonrepp/trolley-management-api:${{ github.sha }}
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
          sed -i'' -e 's/DOCKERHUB_USERNAME/${{ secrets.DOCKERHUB_USERNAME }}/g' -e 's/DOCKERHUB_REPOSITORY/trolley-management-api/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' -e "s/DOCKER_CONFIG/$DOCKER_CONFIG/g" ./build/trolley-management-service.yml
          kubectl delete configmap trolley-management-api-config
          cat << EndOfMessage 
          ${{ secrets.ENV_FILE }}
          EndOfMessage > ./api/.env
          kubectl create configmap trolley-management-api-config --from-env-file=./api/.env -o yaml
          kubectl apply -f ./build/trolley-management-service.yml
          